services:
  db:
    image: postgres:alpine
    container_name: olymprun_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: olymprun_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - olymprun

  backend:
    build: ./backend
    container_name: olymprun_backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      BACKEND_PORT: 8000
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: olymprun_db
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/olymprun_db?schema=public
    volumes:
      - ./shared:/app/shared:ro
    command: sh -c "npx prisma migrate deploy && npx prisma generate && npm run start"
    networks:
      - olymprun

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        SHARED_PATH: "./shared"
        PORT: 3000
        VITE_API_URL: "/api"
    container_name: olymprun_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - olymprun
    volumes:
      - ./shared:/app/shared:ro
      - frontend_build:/frontend_build

  nginx:
    image: nginx:alpine
    container_name: olymprun_nginx
    depends_on:
      - frontend
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - frontend_build:/usr/share/nginx/html:ro
    networks:
      - olymprun

volumes:
  db_data:
  frontend_build:

networks:
  olymprun:
